config/routes.rb
Rails.application.routes.draw do
  get 'rooms/show'
  root to: 'sessions#new'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:index, :new, :create, :show, :edit, :update]
  resources :relationships, only: [:create, :destroy]

  resources :conversations do
    resources :messages
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  # 会話はUserの概念をsenderとrecipientに分けた形でアソシエーションする。
  belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
  belongs_to :recipient, foreign_key: :recipient_id, class_name: 'User'
  # 一つの会話はメッセージをたくさん含む一対多。
  has_many :messages, dependent: :destroy
  # [:sender_id, :recipient_id]が同じ組み合わせで保存されないようにするためのバリデーションを設定。
  validates_uniqueness_of :sender_id, scope: :recipient_id
  # 下記で解説
  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND  conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  end
  # 下記で解説
  def target_user(current_user)
    if sender_id == current_user.id
      User.find(recipient_id)
    elsif recipient_id == current_user.id
      User.find(sender_id)
    end
  end
end

app/models/message.rb
class Message < ApplicationRecord
  after_create_commit { MessageBroadcastJob.perform_later self }
  
  belongs_to :conversation
  belongs_to :user
  validates_presence_of :body, :conversation_id, :user_id
  def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :followed, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, on: :create

  has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  mount_uploader :image, ImageUploader

  #指定のユーザをフォローする
  def follow!(other_user)
    active_relationships.create!(followed_id: other_user.id)
  end
  #フォローしているかどうかを確認する
  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end
  #指定のユーザのフォローを解除する
  def unfollow!(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def authenticate_user
    # 現在ログイン中のユーザが存在しない場合、ログインページにリダイレクトさせる。
    if @current_user == nil
      flash[:notice] = t('notice.login_needed')
      redirect_to new_session_path
    end
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  # Deviseを使用しているならif logged_in?の代わりに下記を使用する。
  # before_action :authenticate_user!
  def index
    @conversations = Conversation.all
  end
  def create
    # 自身で作ったログイン機能であれば、独自実装してあるはずの
    # logged_in?メソッドを使用して、ログイン時のみ会話を保存できるようにする。
    if logged_in?
      if Conversation.between(params[:sender_id], params[:recipient_id]).present?
        @conversation = Conversation.between(params[:sender_id], params[:recipient_id]).first
      else
        @conversation = Conversation.create!(conversation_params)
      end
      redirect_to conversation_messages_path(@conversation)
    else  
      redirect_to root_path
    end  
  end
  private
  def conversation_params
    params.permit(:sender_id, :recipient_id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action do
    @conversation = Conversation.find(params[:conversation_id])
  end

  def index

    #会話相手ユーザーのIDを@opposite_idに格納
    if @conversation.sender_id == current_user.id
      @opposite_id = @conversation.recipient_id
    else
      @opposite_id = @conversation.sender_id
    end
    #会話相手ユーザーのテーブルを@opposite_userに格納
    @opposite_user = User.find(@opposite_id)
    # indexアクションに書かれたこれらの記載は、
    # 一つ一つの部分で何をしているかの理解をわかりやすくするために
    # このような記載にしていますが、実戦で用いるのには少々冗長なコードとなっているので
    # 余力のある人はコードのリファクタリングにも挑戦してみましょう！
    @messages = @conversation.messages
    # if @messages.length > 10
    #   @over_ten = true
    #   @messages = Message.where(id: @messages[-10..-1].pluck(:id))
    # end
    # if params[:m]
    #   @over_ten = false
    #   @messages = @conversation.messages
    # end
    # if @messages.last
    #   @messages.where.not(user_id: current_user.id).update_all(read: true)
    # end
    @messages = @messages.order(:created_at)
    @message = @conversation.messages.build
  end

  def create
    @message = @conversation.messages.build(message_params)
    if @message.save
      redirect_to conversation_messages_path(@conversation)
    else
      render 'index'
    end
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy
    redirect_to conversation_messages_path(@conversation)
  end

  private
  def message_params
    params.require(:message).permit(:body, :user_id)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  # Deviseを使用しているならif logged_in?の代わりに下記を使用する。
  # before_action :authenticate_user!
  respond_to? :js # 存在するアクションのrespondを全てjsで返す場合はこのような記述でも可能。
  def create
    # 自身で作ったログイン機能であれば、独自実装してあるはずの
    # logged_in?メソッドを使用して、ログイン時のみフォローできるようにする。
    if logged_in?
      @user = User.find(params[:relationship][:followed_id])
      current_user.follow!(@user)
    end  
  end
  
  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow!(@user)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def show
    @messages = Message.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "プロフィールを編集しました！"
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :image, :image_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageAcApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="head_block">
      <div>
        <%= link_to image_tag("left_arrow.png", class:"left_arrow"), users_path if logged_in? %>
      </div>
      <div class="header_name">
        <% unless @opposite_user == nil %>
          <%= @opposite_user.name %>
        <% end %>
      </div>
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>
      <div>
        <% if logged_in? %>
          <div class="header_right">
            <%= link_to image_tag("person.png", class:"head_person"), user_path(current_user.id) %>
          </div>
          <div class="header_right">
            <%= link_to image_tag("door.png", class:"head_door"), session_path(current_user.id), method: :delete %>
            <% else %>
              <%= link_to "Sign up", new_user_path %>
              <%= link_to "Login", new_session_path %>
            <% end %>
          </div>
      </div>
    </div>
    <%= yield %>

  </body>
</html>

app/views/messages/_message.html.erb
<div class="latest_box">
  <div class="latest_span">
    <%= image_tag message.user.image.url, class: "profile_message_img" %>
  </div>
  <div class="latest_message">
    <p><%= message.body %></p>
  </div>
</div>

app/views/messages/index.html.erb
<main>
<div id="bottom_block">
  <div class="input_text">
    <%= form_with(model: [@conversation, @message]) do |f| %>
      <div class="scroll_down">
        <%= image_tag "pics.png", class:"message_pics" %>
      </div>
      <%= f.text_area :body, id: "form-control", placeholder: "メッセージを入力", onkeyup: "GetHeight();" %>
      <%= f.text_field :user_id, value: current_user.id, type: "hidden" %>
      <%= f.submit "送信", class: "submit_buttom" %>
    <% end %>
  </div>
</div>
<div class="header_space"></div>
<div class="ui segment">
  <% @messages.each do |message| %>
    <% if message.body.present? %>
      <div class="item">

        <% if message.user == current_user %>
          <div class="delete_box">
          <% if current_user.id == message.user.id %>
            <%= link_to '削除', conversation_message_path(@conversation.id,message.id), class: "delete_message", method: :delete %>
          <% end %>
          </div>
          <div class="self-container">
            <div class="past_self_message">

        <% else %>
          <div class="partner-container">
            <div class="partner_span">
              <%= image_tag @opposite_user.image.url, class: "profile_message_img" %>
            </div>
            <div class="past_partner_message">
        <% end %>
          
            <i class="right triangle icon"></i>
            <%= message.body %>
            <% if message.user == current_user %>
              <%#= message.read ? '既読' : '未読' %>
            <% end %>

          </div>
        </div>

      </div>
    <% end %>
  <% end %>
</div>

<div class="partner-container">
  <div id="conversation_id_is_<%= @opposite_id %><%= @conversation.id %>"></div>
</div>

</main>

<script src="https://cdn.jsdelivr.net/npm/vue@2.6.11"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery-autosize@1.18.18/jquery.autosize.min.js"></script>

<script>
  $(function(){
    $('textarea').autosize();
  });
</script>

<script>
    (function() {
        const target = document.getElementById("form-control");
        const observer = new MutationObserver(function() {
            console.log(target.style.width, target.style.height);
            let element = document.getElementById('bottom_block');
            let text_area_height = document.getElementById('form-control').clientHeight;
            text_area_height = text_area_height + 40;
            element.style.height = text_area_height + "px";
        });

        const options = {
            attriblutes: true,
            attributeFilter: ["style"]
        };
        observer.observe(target, options);
    })();
</script>

app/views/relationships/create.html.erb
<h1>Relationships#create</h1>
<p>Find me in app/views/relationships/create.html.erb</p>

app/views/relationships/create.js.erb
$("#follow_form_"+"<%= @user.id %>").html("<%= escape_javascript(render partial: 'users/follow_form', locals: { user: @user } ) %>")

app/views/relationships/destroy.html.erb
<h1>Relationships#destroy</h1>
<p>Find me in app/views/relationships/destroy.html.erb</p>

app/views/relationships/destroy.js.erb
$("#follow_form_"+"<%= @user.id %>").html("<%= escape_javascript(render partial: 'users/follow_form', locals: { user: @user } ) %>")

app/views/rooms/show.html.erb
<h1>Chat room</h1>

<div id="messages">
  <%= render @messages %>
</div>

<form>
  <label>Say something:</label><br>
  <input type="text" data-behavior="room_speaker">
</form>

app/views/users/_follow_form.html.erb
<div id="follow_form_<%= user.id %>">
  <% unless current_user.following?(user) %>
    <%= form_with(model: current_user.active_relationships.build(followed_id: user.id)) do |f| %>
      <%= f.hidden_field :followed_id %>
      <%= f.submit "フォロー" %>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.active_relationships.find_by(followed_id: user.id), method: :delete ) do |f| %>
      <%= f.submit "つながりを解除" %>
    <% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<br>
<br>
<br>
<h1>Sign up</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :image %>
  <%= f.file_field :image %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit "プロフィールを更新" %>
<% end %>

app/views/users/index.html.erb
<br>
<br>
<br>
<h2>ユーザー一覧</h2>
<% @users.each do |user| %>
  <% if user.id != current_user.id %>
      <div class="item"> 
        <%= "★" %>
        <%= user.name %>
        <%= link_to 'メッセージ', conversations_path(sender_id: current_user.id, recipient_id: user.id), class: "all_user", method: :post %>
      </div>
    <%#= render 'follow_form', user: user %> <!-- フォロー機能が実装されて入ればこの一文も必要 -->
  <% end %>
  <br>
<% end %>

app/views/users/new.html.erb
<br>
<br>
<br>

<h1>Sign up</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<br>
<br>
<br>
<h1><%= @user.name %>のページ</h1>
<p>メールアドレス: <%= @user.email %></p>

<p>
  <strong>Image:</strong>
  <% unless @user.image.url == nil %>
    <%= image_tag @user.image.url, class: "profile_show_img" %>
  <% end %>
</p>

<%= link_to "プロフィールを編集する", edit_user_path(@user.id) %>